@echo off
rem
rem This file is generated by the Qt installer
rem

echo Setting up a Qt environment...

rem set QTDIR=C:\Qt\Qt5.14.2-win64-msvc2017\5.14.2\msvc2017_64
set QTDIR=C:\Qt\Qt5.15.0-win64

echo -- QTDIR set to %QTDIR%
set PATH=%QTDIR%\bin;%PATH%
echo -- Added %QTDIR%\bin to PATH



