@echo off
rem
rem This file is generated by the Qt installer
rem

echo Setting up a Qt environment...

set QTDIR=C:\Qt\Qt5.12.5-win64\5.12.5\msvc2017_64
echo -- QTDIR set to %QTDIR%
set PATH=%QTDIR%\bin;%PATH%
echo -- Added %QTDIR%\bin to PATH



